# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YXObserverAndKVO' do
    pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YXObserverAndKVO

  target 'YXObserverAndKVOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YXObserverAndKVOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
